/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as SharesRouteImport } from './routes/shares'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoutesRouteImport } from './routes/routes'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as MonitorRouteImport } from './routes/monitor'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as CronRouteImport } from './routes/cron'
import { Route as ActorsRouteImport } from './routes/actors'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProvidersIdRouteImport } from './routes/providers.$id'
import { Route as IntegrationsIdRouteImport } from './routes/integrations.$id'
import { Route as CronNewRouteImport } from './routes/cron.new'
import { Route as AdminConversationsRouteImport } from './routes/admin.conversations'
import { Route as ActorsNewRouteImport } from './routes/actors.new'
import { Route as ActorsIdRouteImport } from './routes/actors.$id'
import { Route as AdminConversationsConversationIdRouteImport } from './routes/admin.conversations.$conversationId'
import { Route as ActorsIdEditRouteImport } from './routes/actors.$id.edit'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const SharesRoute = SharesRouteImport.update({
  id: '/shares',
  path: '/shares',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRoute = RoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorRoute = MonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const CronRoute = CronRouteImport.update({
  id: '/cron',
  path: '/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ActorsRoute = ActorsRouteImport.update({
  id: '/actors',
  path: '/actors',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIdRoute = ProvidersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProvidersRoute,
} as any)
const IntegrationsIdRoute = IntegrationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => IntegrationsRoute,
} as any)
const CronNewRoute = CronNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CronRoute,
} as any)
const AdminConversationsRoute = AdminConversationsRouteImport.update({
  id: '/admin/conversations',
  path: '/admin/conversations',
  getParentRoute: () => rootRouteImport,
} as any)
const ActorsNewRoute = ActorsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ActorsRoute,
} as any)
const ActorsIdRoute = ActorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ActorsRoute,
} as any)
const AdminConversationsConversationIdRoute =
  AdminConversationsConversationIdRouteImport.update({
    id: '/$conversationId',
    path: '/$conversationId',
    getParentRoute: () => AdminConversationsRoute,
  } as any)
const ActorsIdEditRoute = ActorsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ActorsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actors': typeof ActorsRouteWithChildren
  '/cron': typeof CronRouteWithChildren
  '/integrations': typeof IntegrationsRouteWithChildren
  '/monitor': typeof MonitorRoute
  '/providers': typeof ProvidersRouteWithChildren
  '/routes': typeof RoutesRoute
  '/settings': typeof SettingsRoute
  '/shares': typeof SharesRoute
  '/workspace': typeof WorkspaceRoute
  '/actors/$id': typeof ActorsIdRouteWithChildren
  '/actors/new': typeof ActorsNewRoute
  '/admin/conversations': typeof AdminConversationsRouteWithChildren
  '/cron/new': typeof CronNewRoute
  '/integrations/$id': typeof IntegrationsIdRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/actors/$id/edit': typeof ActorsIdEditRoute
  '/admin/conversations/$conversationId': typeof AdminConversationsConversationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actors': typeof ActorsRouteWithChildren
  '/cron': typeof CronRouteWithChildren
  '/integrations': typeof IntegrationsRouteWithChildren
  '/monitor': typeof MonitorRoute
  '/providers': typeof ProvidersRouteWithChildren
  '/routes': typeof RoutesRoute
  '/settings': typeof SettingsRoute
  '/shares': typeof SharesRoute
  '/workspace': typeof WorkspaceRoute
  '/actors/$id': typeof ActorsIdRouteWithChildren
  '/actors/new': typeof ActorsNewRoute
  '/admin/conversations': typeof AdminConversationsRouteWithChildren
  '/cron/new': typeof CronNewRoute
  '/integrations/$id': typeof IntegrationsIdRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/actors/$id/edit': typeof ActorsIdEditRoute
  '/admin/conversations/$conversationId': typeof AdminConversationsConversationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actors': typeof ActorsRouteWithChildren
  '/cron': typeof CronRouteWithChildren
  '/integrations': typeof IntegrationsRouteWithChildren
  '/monitor': typeof MonitorRoute
  '/providers': typeof ProvidersRouteWithChildren
  '/routes': typeof RoutesRoute
  '/settings': typeof SettingsRoute
  '/shares': typeof SharesRoute
  '/workspace': typeof WorkspaceRoute
  '/actors/$id': typeof ActorsIdRouteWithChildren
  '/actors/new': typeof ActorsNewRoute
  '/admin/conversations': typeof AdminConversationsRouteWithChildren
  '/cron/new': typeof CronNewRoute
  '/integrations/$id': typeof IntegrationsIdRoute
  '/providers/$id': typeof ProvidersIdRoute
  '/actors/$id/edit': typeof ActorsIdEditRoute
  '/admin/conversations/$conversationId': typeof AdminConversationsConversationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actors'
    | '/cron'
    | '/integrations'
    | '/monitor'
    | '/providers'
    | '/routes'
    | '/settings'
    | '/shares'
    | '/workspace'
    | '/actors/$id'
    | '/actors/new'
    | '/admin/conversations'
    | '/cron/new'
    | '/integrations/$id'
    | '/providers/$id'
    | '/actors/$id/edit'
    | '/admin/conversations/$conversationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actors'
    | '/cron'
    | '/integrations'
    | '/monitor'
    | '/providers'
    | '/routes'
    | '/settings'
    | '/shares'
    | '/workspace'
    | '/actors/$id'
    | '/actors/new'
    | '/admin/conversations'
    | '/cron/new'
    | '/integrations/$id'
    | '/providers/$id'
    | '/actors/$id/edit'
    | '/admin/conversations/$conversationId'
  id:
    | '__root__'
    | '/'
    | '/actors'
    | '/cron'
    | '/integrations'
    | '/monitor'
    | '/providers'
    | '/routes'
    | '/settings'
    | '/shares'
    | '/workspace'
    | '/actors/$id'
    | '/actors/new'
    | '/admin/conversations'
    | '/cron/new'
    | '/integrations/$id'
    | '/providers/$id'
    | '/actors/$id/edit'
    | '/admin/conversations/$conversationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActorsRoute: typeof ActorsRouteWithChildren
  CronRoute: typeof CronRouteWithChildren
  IntegrationsRoute: typeof IntegrationsRouteWithChildren
  MonitorRoute: typeof MonitorRoute
  ProvidersRoute: typeof ProvidersRouteWithChildren
  RoutesRoute: typeof RoutesRoute
  SettingsRoute: typeof SettingsRoute
  SharesRoute: typeof SharesRoute
  WorkspaceRoute: typeof WorkspaceRoute
  AdminConversationsRoute: typeof AdminConversationsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shares': {
      id: '/shares'
      path: '/shares'
      fullPath: '/shares'
      preLoaderRoute: typeof SharesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes': {
      id: '/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor': {
      id: '/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof MonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cron': {
      id: '/cron'
      path: '/cron'
      fullPath: '/cron'
      preLoaderRoute: typeof CronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actors': {
      id: '/actors'
      path: '/actors'
      fullPath: '/actors'
      preLoaderRoute: typeof ActorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/$id': {
      id: '/providers/$id'
      path: '/$id'
      fullPath: '/providers/$id'
      preLoaderRoute: typeof ProvidersIdRouteImport
      parentRoute: typeof ProvidersRoute
    }
    '/integrations/$id': {
      id: '/integrations/$id'
      path: '/$id'
      fullPath: '/integrations/$id'
      preLoaderRoute: typeof IntegrationsIdRouteImport
      parentRoute: typeof IntegrationsRoute
    }
    '/cron/new': {
      id: '/cron/new'
      path: '/new'
      fullPath: '/cron/new'
      preLoaderRoute: typeof CronNewRouteImport
      parentRoute: typeof CronRoute
    }
    '/admin/conversations': {
      id: '/admin/conversations'
      path: '/admin/conversations'
      fullPath: '/admin/conversations'
      preLoaderRoute: typeof AdminConversationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actors/new': {
      id: '/actors/new'
      path: '/new'
      fullPath: '/actors/new'
      preLoaderRoute: typeof ActorsNewRouteImport
      parentRoute: typeof ActorsRoute
    }
    '/actors/$id': {
      id: '/actors/$id'
      path: '/$id'
      fullPath: '/actors/$id'
      preLoaderRoute: typeof ActorsIdRouteImport
      parentRoute: typeof ActorsRoute
    }
    '/admin/conversations/$conversationId': {
      id: '/admin/conversations/$conversationId'
      path: '/$conversationId'
      fullPath: '/admin/conversations/$conversationId'
      preLoaderRoute: typeof AdminConversationsConversationIdRouteImport
      parentRoute: typeof AdminConversationsRoute
    }
    '/actors/$id/edit': {
      id: '/actors/$id/edit'
      path: '/edit'
      fullPath: '/actors/$id/edit'
      preLoaderRoute: typeof ActorsIdEditRouteImport
      parentRoute: typeof ActorsIdRoute
    }
  }
}

interface ActorsIdRouteChildren {
  ActorsIdEditRoute: typeof ActorsIdEditRoute
}

const ActorsIdRouteChildren: ActorsIdRouteChildren = {
  ActorsIdEditRoute: ActorsIdEditRoute,
}

const ActorsIdRouteWithChildren = ActorsIdRoute._addFileChildren(
  ActorsIdRouteChildren,
)

interface ActorsRouteChildren {
  ActorsIdRoute: typeof ActorsIdRouteWithChildren
  ActorsNewRoute: typeof ActorsNewRoute
}

const ActorsRouteChildren: ActorsRouteChildren = {
  ActorsIdRoute: ActorsIdRouteWithChildren,
  ActorsNewRoute: ActorsNewRoute,
}

const ActorsRouteWithChildren =
  ActorsRoute._addFileChildren(ActorsRouteChildren)

interface CronRouteChildren {
  CronNewRoute: typeof CronNewRoute
}

const CronRouteChildren: CronRouteChildren = {
  CronNewRoute: CronNewRoute,
}

const CronRouteWithChildren = CronRoute._addFileChildren(CronRouteChildren)

interface IntegrationsRouteChildren {
  IntegrationsIdRoute: typeof IntegrationsIdRoute
}

const IntegrationsRouteChildren: IntegrationsRouteChildren = {
  IntegrationsIdRoute: IntegrationsIdRoute,
}

const IntegrationsRouteWithChildren = IntegrationsRoute._addFileChildren(
  IntegrationsRouteChildren,
)

interface ProvidersRouteChildren {
  ProvidersIdRoute: typeof ProvidersIdRoute
}

const ProvidersRouteChildren: ProvidersRouteChildren = {
  ProvidersIdRoute: ProvidersIdRoute,
}

const ProvidersRouteWithChildren = ProvidersRoute._addFileChildren(
  ProvidersRouteChildren,
)

interface AdminConversationsRouteChildren {
  AdminConversationsConversationIdRoute: typeof AdminConversationsConversationIdRoute
}

const AdminConversationsRouteChildren: AdminConversationsRouteChildren = {
  AdminConversationsConversationIdRoute: AdminConversationsConversationIdRoute,
}

const AdminConversationsRouteWithChildren =
  AdminConversationsRoute._addFileChildren(AdminConversationsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActorsRoute: ActorsRouteWithChildren,
  CronRoute: CronRouteWithChildren,
  IntegrationsRoute: IntegrationsRouteWithChildren,
  MonitorRoute: MonitorRoute,
  ProvidersRoute: ProvidersRouteWithChildren,
  RoutesRoute: RoutesRoute,
  SettingsRoute: SettingsRoute,
  SharesRoute: SharesRoute,
  WorkspaceRoute: WorkspaceRoute,
  AdminConversationsRoute: AdminConversationsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
