/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoutesRouteImport } from './routes/routes'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as MonitorRouteImport } from './routes/monitor'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as CharactersRouteImport } from './routes/characters'
import { Route as ActorsRouteImport } from './routes/actors'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProvidersIdRouteImport } from './routes/providers.$id'
import { Route as IntegrationsIdRouteImport } from './routes/integrations.$id'
import { Route as ChatDialogIdRouteImport } from './routes/chat.$dialogId'
import { Route as CharactersIdRouteImport } from './routes/characters.$id'
import { Route as ActorsIdRouteImport } from './routes/actors.$id'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutesRoute = RoutesRouteImport.update({
  id: '/routes',
  path: '/routes',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const MonitorRoute = MonitorRouteImport.update({
  id: '/monitor',
  path: '/monitor',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersRoute = CharactersRouteImport.update({
  id: '/characters',
  path: '/characters',
  getParentRoute: () => rootRouteImport,
} as any)
const ActorsRoute = ActorsRouteImport.update({
  id: '/actors',
  path: '/actors',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersIdRoute = ProvidersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProvidersRoute,
} as any)
const IntegrationsIdRoute = IntegrationsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => IntegrationsRoute,
} as any)
const ChatDialogIdRoute = ChatDialogIdRouteImport.update({
  id: '/$dialogId',
  path: '/$dialogId',
  getParentRoute: () => ChatRoute,
} as any)
const CharactersIdRoute = CharactersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CharactersRoute,
} as any)
const ActorsIdRoute = ActorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ActorsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/actors': typeof ActorsRouteWithChildren
  '/characters': typeof CharactersRouteWithChildren
  '/chat': typeof ChatRouteWithChildren
  '/integrations': typeof IntegrationsRouteWithChildren
  '/monitor': typeof MonitorRoute
  '/providers': typeof ProvidersRouteWithChildren
  '/routes': typeof RoutesRoute
  '/settings': typeof SettingsRoute
  '/actors/$id': typeof ActorsIdRoute
  '/characters/$id': typeof CharactersIdRoute
  '/chat/$dialogId': typeof ChatDialogIdRoute
  '/integrations/$id': typeof IntegrationsIdRoute
  '/providers/$id': typeof ProvidersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/actors': typeof ActorsRouteWithChildren
  '/characters': typeof CharactersRouteWithChildren
  '/chat': typeof ChatRouteWithChildren
  '/integrations': typeof IntegrationsRouteWithChildren
  '/monitor': typeof MonitorRoute
  '/providers': typeof ProvidersRouteWithChildren
  '/routes': typeof RoutesRoute
  '/settings': typeof SettingsRoute
  '/actors/$id': typeof ActorsIdRoute
  '/characters/$id': typeof CharactersIdRoute
  '/chat/$dialogId': typeof ChatDialogIdRoute
  '/integrations/$id': typeof IntegrationsIdRoute
  '/providers/$id': typeof ProvidersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/actors': typeof ActorsRouteWithChildren
  '/characters': typeof CharactersRouteWithChildren
  '/chat': typeof ChatRouteWithChildren
  '/integrations': typeof IntegrationsRouteWithChildren
  '/monitor': typeof MonitorRoute
  '/providers': typeof ProvidersRouteWithChildren
  '/routes': typeof RoutesRoute
  '/settings': typeof SettingsRoute
  '/actors/$id': typeof ActorsIdRoute
  '/characters/$id': typeof CharactersIdRoute
  '/chat/$dialogId': typeof ChatDialogIdRoute
  '/integrations/$id': typeof IntegrationsIdRoute
  '/providers/$id': typeof ProvidersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/actors'
    | '/characters'
    | '/chat'
    | '/integrations'
    | '/monitor'
    | '/providers'
    | '/routes'
    | '/settings'
    | '/actors/$id'
    | '/characters/$id'
    | '/chat/$dialogId'
    | '/integrations/$id'
    | '/providers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/actors'
    | '/characters'
    | '/chat'
    | '/integrations'
    | '/monitor'
    | '/providers'
    | '/routes'
    | '/settings'
    | '/actors/$id'
    | '/characters/$id'
    | '/chat/$dialogId'
    | '/integrations/$id'
    | '/providers/$id'
  id:
    | '__root__'
    | '/'
    | '/actors'
    | '/characters'
    | '/chat'
    | '/integrations'
    | '/monitor'
    | '/providers'
    | '/routes'
    | '/settings'
    | '/actors/$id'
    | '/characters/$id'
    | '/chat/$dialogId'
    | '/integrations/$id'
    | '/providers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActorsRoute: typeof ActorsRouteWithChildren
  CharactersRoute: typeof CharactersRouteWithChildren
  ChatRoute: typeof ChatRouteWithChildren
  IntegrationsRoute: typeof IntegrationsRouteWithChildren
  MonitorRoute: typeof MonitorRoute
  ProvidersRoute: typeof ProvidersRouteWithChildren
  RoutesRoute: typeof RoutesRoute
  SettingsRoute: typeof SettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routes': {
      id: '/routes'
      path: '/routes'
      fullPath: '/routes'
      preLoaderRoute: typeof RoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/monitor': {
      id: '/monitor'
      path: '/monitor'
      fullPath: '/monitor'
      preLoaderRoute: typeof MonitorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters': {
      id: '/characters'
      path: '/characters'
      fullPath: '/characters'
      preLoaderRoute: typeof CharactersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/actors': {
      id: '/actors'
      path: '/actors'
      fullPath: '/actors'
      preLoaderRoute: typeof ActorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers/$id': {
      id: '/providers/$id'
      path: '/$id'
      fullPath: '/providers/$id'
      preLoaderRoute: typeof ProvidersIdRouteImport
      parentRoute: typeof ProvidersRoute
    }
    '/integrations/$id': {
      id: '/integrations/$id'
      path: '/$id'
      fullPath: '/integrations/$id'
      preLoaderRoute: typeof IntegrationsIdRouteImport
      parentRoute: typeof IntegrationsRoute
    }
    '/chat/$dialogId': {
      id: '/chat/$dialogId'
      path: '/$dialogId'
      fullPath: '/chat/$dialogId'
      preLoaderRoute: typeof ChatDialogIdRouteImport
      parentRoute: typeof ChatRoute
    }
    '/characters/$id': {
      id: '/characters/$id'
      path: '/$id'
      fullPath: '/characters/$id'
      preLoaderRoute: typeof CharactersIdRouteImport
      parentRoute: typeof CharactersRoute
    }
    '/actors/$id': {
      id: '/actors/$id'
      path: '/$id'
      fullPath: '/actors/$id'
      preLoaderRoute: typeof ActorsIdRouteImport
      parentRoute: typeof ActorsRoute
    }
  }
}

interface ActorsRouteChildren {
  ActorsIdRoute: typeof ActorsIdRoute
}

const ActorsRouteChildren: ActorsRouteChildren = {
  ActorsIdRoute: ActorsIdRoute,
}

const ActorsRouteWithChildren =
  ActorsRoute._addFileChildren(ActorsRouteChildren)

interface CharactersRouteChildren {
  CharactersIdRoute: typeof CharactersIdRoute
}

const CharactersRouteChildren: CharactersRouteChildren = {
  CharactersIdRoute: CharactersIdRoute,
}

const CharactersRouteWithChildren = CharactersRoute._addFileChildren(
  CharactersRouteChildren,
)

interface ChatRouteChildren {
  ChatDialogIdRoute: typeof ChatDialogIdRoute
}

const ChatRouteChildren: ChatRouteChildren = {
  ChatDialogIdRoute: ChatDialogIdRoute,
}

const ChatRouteWithChildren = ChatRoute._addFileChildren(ChatRouteChildren)

interface IntegrationsRouteChildren {
  IntegrationsIdRoute: typeof IntegrationsIdRoute
}

const IntegrationsRouteChildren: IntegrationsRouteChildren = {
  IntegrationsIdRoute: IntegrationsIdRoute,
}

const IntegrationsRouteWithChildren = IntegrationsRoute._addFileChildren(
  IntegrationsRouteChildren,
)

interface ProvidersRouteChildren {
  ProvidersIdRoute: typeof ProvidersIdRoute
}

const ProvidersRouteChildren: ProvidersRouteChildren = {
  ProvidersIdRoute: ProvidersIdRoute,
}

const ProvidersRouteWithChildren = ProvidersRoute._addFileChildren(
  ProvidersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActorsRoute: ActorsRouteWithChildren,
  CharactersRoute: CharactersRouteWithChildren,
  ChatRoute: ChatRouteWithChildren,
  IntegrationsRoute: IntegrationsRouteWithChildren,
  MonitorRoute: MonitorRoute,
  ProvidersRoute: ProvidersRouteWithChildren,
  RoutesRoute: RoutesRoute,
  SettingsRoute: SettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
